# Generated by Django 5.0.3 on 2024-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Generate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("qr_code", models.ImageField(blank=True, upload_to="qrcodes/")),
                ("date", models.DateField()),
            ],
        ),
    ]
