# Generated by Django 5.0.2 on 2024-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secQr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generate",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
