# Generated by Django 5.0.2 on 2024-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=122, unique=True)),
                ("first_name", models.CharField(max_length=125)),
                ("last_name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
                (
                    "gender",
                    models.SmallIntegerField(choices=[(1, "male"), (2, "Female")]),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
