# Generated by Django 5.0.3 on 2024-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_blacklistedtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlacklistedToken",
        ),
    ]
