# Generated by Django 5.0.3 on 2024-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_delete_blacklistedtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
