# Generated by Django 5.0.3 on 2024-04-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Generate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("qr_code", models.ImageField(blank=True, upload_to="qrcodes/")),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "_app_prefix_hidden",
                    models.CharField(default="SecQR", editable=False, max_length=50),
                ),
                (
                    "app_prefix",
                    models.CharField(default="SecQR", editable=False, max_length=50),
                ),
                ("url_status", models.CharField(default="NONE", max_length=200)),
                ("generation_status", models.CharField(default="NONE", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_prefix",
                    models.CharField(default="SecQR", editable=False, max_length=50),
                ),
                ("link", models.CharField(max_length=200)),
                ("link_status", models.CharField(default="NONE", max_length=200)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verify_qr_legitimacy",
                    models.CharField(default="NONE", max_length=200),
                ),
                ("malware_detected", models.TextField(default="NONE")),
                ("malware_detected_tool", models.TextField(default="NONE")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
