# Generated by Django 5.0.3 on 2024-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secqr_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="scan_images/"),
        ),
    ]
