# Generated by Django 5.0.3 on 2024-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secqr_api", "0002_alter_scan_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generate",
            name="generation_status",
            field=models.CharField(default="NONE", max_length=20),
        ),
        migrations.AlterField(
            model_name="generate",
            name="url_status",
            field=models.CharField(default="NONE", max_length=20),
        ),
        migrations.AlterField(
            model_name="scan",
            name="link_status",
            field=models.CharField(default="NONE", max_length=20),
        ),
        migrations.AlterField(
            model_name="scan",
            name="verify_qr_legitimacy",
            field=models.CharField(default="NONE", max_length=30),
        ),
    ]
