# Generated by Django 5.0.3 on 2024-04-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secqr_api', '0008_generate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='report',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
